name: more_main_axis_alignment
description: Just like Flex(),but this package provides more MainAxisAlignment.
version: 1.0.0
repository: https://github.com/w830207/more_main_axis_alignment

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
